<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsPackable>True</IsPackable>
    <DefineConstants>$(DefineConstants);RESHARPER</DefineConstants>
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.ReSharper.SDK" Version="$(SdkVersion)" PrivateAssets="all" />
    <PackageReference Include="Wave" Version="$(WaveVersion)" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\dependencies.json" PackagePath="" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName)\$(Configuration)\$(AssemblyName).dll" PackagePath="dotFiles" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName)\$(Configuration)\$(AssemblyName).pdb" PackagePath="dotFiles" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName).Rider\$(Configuration)\Helix.MixinLanguage.dll" PackagePath="dotFiles" Pack="true" Visible="false" />
    <Content Include="bin\$(AssemblyName).Rider\$(Configuration)\Helix.MixinLanguage.pdb" PackagePath="dotFiles" Pack="true" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="HelixLiveTemplates.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>HelixLiveTemplates.DotSettings</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
  </ItemGroup>

</Project>
