<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>HelixRider</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <IsPackable>false</IsPackable>
    <DefineConstants>$(DefineConstants);RIDER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Rider.SDK" Version="$(SdkVersion)" />
    <ProjectReference Include="..\..\..\..\Hix.MixinGenerator\Hix.MixinGenerator.csproj" />
    <Compile Include="..\..\..\..\Hix.Standalone\Analysis\*.cs"
             Link="HixStandaloneAnalysis\%(Filename)%(Extension)" />
    <Compile Include="..\..\..\..\Hix\IsExternalInit.cs"
             Link="Compatibility\IsExternalInit.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="HelixLiveTemplates.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>HelixLiveTemplates.DotSettings</DependentUpon>
      <DesignTime>True</DesignTime>
    </Compile>
  </ItemGroup>

</Project>
