//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace HelixRider.Protocol
{
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:9</p>
  /// </summary>
  public class HelixExpressionModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<MixinExpressionRequest, MixinExpressionResponse> GetMixinExpressionRanges => _GetMixinExpressionRanges;
    [NotNull] public IRdEndpoint<MixinExpressionRequest, MixinContributionsResponse> GetMixinContributions => _GetMixinContributions;
    [NotNull] public IViewableProperty<bool> IsHelixEnabled => _IsHelixEnabled;
    
    //private fields
    [NotNull] private readonly RdCall<MixinExpressionRequest, MixinExpressionResponse> _GetMixinExpressionRanges;
    [NotNull] private readonly RdCall<MixinExpressionRequest, MixinContributionsResponse> _GetMixinContributions;
    [NotNull] private readonly RdProperty<bool> _IsHelixEnabled;
    
    //primary constructor
    private HelixExpressionModel(
      [NotNull] RdCall<MixinExpressionRequest, MixinExpressionResponse> getMixinExpressionRanges,
      [NotNull] RdCall<MixinExpressionRequest, MixinContributionsResponse> getMixinContributions,
      [NotNull] RdProperty<bool> isHelixEnabled
    )
    {
      if (getMixinExpressionRanges == null) throw new ArgumentNullException("getMixinExpressionRanges");
      if (getMixinContributions == null) throw new ArgumentNullException("getMixinContributions");
      if (isHelixEnabled == null) throw new ArgumentNullException("isHelixEnabled");
      
      _GetMixinExpressionRanges = getMixinExpressionRanges;
      _GetMixinContributions = getMixinContributions;
      _IsHelixEnabled = isHelixEnabled;
      _IsHelixEnabled.OptimizeNested = true;
      _GetMixinExpressionRanges.Async = true;
      _GetMixinContributions.Async = true;
      BindableChildren.Add(new KeyValuePair<string, object>("getMixinExpressionRanges", _GetMixinExpressionRanges));
      BindableChildren.Add(new KeyValuePair<string, object>("getMixinContributions", _GetMixinContributions));
      BindableChildren.Add(new KeyValuePair<string, object>("isHelixEnabled", _IsHelixEnabled));
    }
    //secondary constructor
    internal HelixExpressionModel (
    ) : this (
      new RdCall<MixinExpressionRequest, MixinExpressionResponse>(MixinExpressionRequest.Read, MixinExpressionRequest.Write, MixinExpressionResponse.Read, MixinExpressionResponse.Write),
      new RdCall<MixinExpressionRequest, MixinContributionsResponse>(MixinExpressionRequest.Read, MixinExpressionRequest.Write, MixinContributionsResponse.Read, MixinContributionsResponse.Write),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -5251956373142778403L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(JetBrains.Rider.Model.IdeRoot), JetBrains.Rider.Model.IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("HelixExpressionModel (");
      using (printer.IndentCookie()) {
        printer.Print("getMixinExpressionRanges = "); _GetMixinExpressionRanges.PrintEx(printer); printer.Println();
        printer.Print("getMixinContributions = "); _GetMixinContributions.PrintEx(printer); printer.Println();
        printer.Print("isHelixEnabled = "); _IsHelixEnabled.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionHelixExpressionModelEx
   {
    public static HelixExpressionModel GetHelixExpressionModel(this JetBrains.Rider.Model.Solution solution)
    {
      return solution.GetOrCreateExtension("helixExpressionModel", () => new HelixExpressionModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:34</p>
  /// </summary>
  public sealed class MixinContribution : IPrintable, IEquatable<MixinContribution>
  {
    //fields
    //public fields
    public int Offset {get; private set;}
    [NotNull] public string Target {get; private set;}
    [NotNull] public string Method {get; private set;}
    [NotNull] public string Mixin {get; private set;}
    public int Priority {get; private set;}
    [NotNull] public string SourceType {get; private set;}
    [NotNull] public string SourceMember {get; private set;}
    [NotNull] public string SourceKind {get; private set;}
    public int SourceParameterCount {get; private set;}
    
    //private fields
    //primary constructor
    public MixinContribution(
      int offset,
      [NotNull] string target,
      [NotNull] string method,
      [NotNull] string mixin,
      int priority,
      [NotNull] string sourceType,
      [NotNull] string sourceMember,
      [NotNull] string sourceKind,
      int sourceParameterCount
    )
    {
      if (target == null) throw new ArgumentNullException("target");
      if (method == null) throw new ArgumentNullException("method");
      if (mixin == null) throw new ArgumentNullException("mixin");
      if (sourceType == null) throw new ArgumentNullException("sourceType");
      if (sourceMember == null) throw new ArgumentNullException("sourceMember");
      if (sourceKind == null) throw new ArgumentNullException("sourceKind");
      
      Offset = offset;
      Target = target;
      Method = method;
      Mixin = mixin;
      Priority = priority;
      SourceType = sourceType;
      SourceMember = sourceMember;
      SourceKind = sourceKind;
      SourceParameterCount = sourceParameterCount;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out int offset, [NotNull] out string target, [NotNull] out string method, [NotNull] out string mixin, out int priority, [NotNull] out string sourceType, [NotNull] out string sourceMember, [NotNull] out string sourceKind, out int sourceParameterCount)
    {
      offset = Offset;
      target = Target;
      method = Method;
      mixin = Mixin;
      priority = Priority;
      sourceType = SourceType;
      sourceMember = SourceMember;
      sourceKind = SourceKind;
      sourceParameterCount = SourceParameterCount;
    }
    //statics
    
    public static CtxReadDelegate<MixinContribution> Read = (ctx, reader) => 
    {
      var offset = reader.ReadInt();
      var target = reader.ReadString();
      var method = reader.ReadString();
      var mixin = reader.ReadString();
      var priority = reader.ReadInt();
      var sourceType = reader.ReadString();
      var sourceMember = reader.ReadString();
      var sourceKind = reader.ReadString();
      var sourceParameterCount = reader.ReadInt();
      var _result = new MixinContribution(offset, target, method, mixin, priority, sourceType, sourceMember, sourceKind, sourceParameterCount);
      return _result;
    };
    
    public static CtxWriteDelegate<MixinContribution> Write = (ctx, writer, value) => 
    {
      writer.Write(value.Offset);
      writer.Write(value.Target);
      writer.Write(value.Method);
      writer.Write(value.Mixin);
      writer.Write(value.Priority);
      writer.Write(value.SourceType);
      writer.Write(value.SourceMember);
      writer.Write(value.SourceKind);
      writer.Write(value.SourceParameterCount);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinContribution) obj);
    }
    public bool Equals(MixinContribution other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Offset == other.Offset && Target == other.Target && Method == other.Method && Mixin == other.Mixin && Priority == other.Priority && SourceType == other.SourceType && SourceMember == other.SourceMember && SourceKind == other.SourceKind && SourceParameterCount == other.SourceParameterCount;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Offset.GetHashCode();
        hash = hash * 31 + Target.GetHashCode();
        hash = hash * 31 + Method.GetHashCode();
        hash = hash * 31 + Mixin.GetHashCode();
        hash = hash * 31 + Priority.GetHashCode();
        hash = hash * 31 + SourceType.GetHashCode();
        hash = hash * 31 + SourceMember.GetHashCode();
        hash = hash * 31 + SourceKind.GetHashCode();
        hash = hash * 31 + SourceParameterCount.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinContribution (");
      using (printer.IndentCookie()) {
        printer.Print("offset = "); Offset.PrintEx(printer); printer.Println();
        printer.Print("target = "); Target.PrintEx(printer); printer.Println();
        printer.Print("method = "); Method.PrintEx(printer); printer.Println();
        printer.Print("mixin = "); Mixin.PrintEx(printer); printer.Println();
        printer.Print("priority = "); Priority.PrintEx(printer); printer.Println();
        printer.Print("sourceType = "); SourceType.PrintEx(printer); printer.Println();
        printer.Print("sourceMember = "); SourceMember.PrintEx(printer); printer.Println();
        printer.Print("sourceKind = "); SourceKind.PrintEx(printer); printer.Println();
        printer.Print("sourceParameterCount = "); SourceParameterCount.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:46</p>
  /// </summary>
  public sealed class MixinContributionsResponse : IPrintable, IEquatable<MixinContributionsResponse>
  {
    //fields
    //public fields
    [NotNull] public MixinContribution[] Contributions {get; private set;}
    
    //private fields
    //primary constructor
    public MixinContributionsResponse(
      [NotNull] MixinContribution[] contributions
    )
    {
      if (contributions == null) throw new ArgumentNullException("contributions");
      
      Contributions = contributions;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out MixinContribution[] contributions)
    {
      contributions = Contributions;
    }
    //statics
    
    public static CtxReadDelegate<MixinContributionsResponse> Read = (ctx, reader) => 
    {
      var contributions = ReadMixinContributionArray(ctx, reader);
      var _result = new MixinContributionsResponse(contributions);
      return _result;
    };
    public static CtxReadDelegate<MixinContribution[]> ReadMixinContributionArray = MixinContribution.Read.Array();
    
    public static CtxWriteDelegate<MixinContributionsResponse> Write = (ctx, writer, value) => 
    {
      WriteMixinContributionArray(ctx, writer, value.Contributions);
    };
    public static  CtxWriteDelegate<MixinContribution[]> WriteMixinContributionArray = MixinContribution.Write.Array();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinContributionsResponse) obj);
    }
    public bool Equals(MixinContributionsResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Contributions.SequenceEqual(other.Contributions);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + Contributions.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinContributionsResponse (");
      using (printer.IndentCookie()) {
        printer.Print("contributions = "); Contributions.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:15</p>
  /// </summary>
  public sealed class MixinExpressionRange : IPrintable, IEquatable<MixinExpressionRange>
  {
    //fields
    //public fields
    public int StartOffset {get; private set;}
    public int EndOffset {get; private set;}
    
    //private fields
    //primary constructor
    public MixinExpressionRange(
      int startOffset,
      int endOffset
    )
    {
      StartOffset = startOffset;
      EndOffset = endOffset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out int startOffset, out int endOffset)
    {
      startOffset = StartOffset;
      endOffset = EndOffset;
    }
    //statics
    
    public static CtxReadDelegate<MixinExpressionRange> Read = (ctx, reader) => 
    {
      var startOffset = reader.ReadInt();
      var endOffset = reader.ReadInt();
      var _result = new MixinExpressionRange(startOffset, endOffset);
      return _result;
    };
    
    public static CtxWriteDelegate<MixinExpressionRange> Write = (ctx, writer, value) => 
    {
      writer.Write(value.StartOffset);
      writer.Write(value.EndOffset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinExpressionRange) obj);
    }
    public bool Equals(MixinExpressionRange other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return StartOffset == other.StartOffset && EndOffset == other.EndOffset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + StartOffset.GetHashCode();
        hash = hash * 31 + EndOffset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinExpressionRange (");
      using (printer.IndentCookie()) {
        printer.Print("startOffset = "); StartOffset.PrintEx(printer); printer.Println();
        printer.Print("endOffset = "); EndOffset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:20</p>
  /// </summary>
  public sealed class MixinExpressionRequest : IPrintable, IEquatable<MixinExpressionRequest>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    [NotNull] public string SourceText {get; private set;}
    public long Revision {get; private set;}
    
    //private fields
    //primary constructor
    public MixinExpressionRequest(
      [NotNull] string filePath,
      [NotNull] string sourceText,
      long revision
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      if (sourceText == null) throw new ArgumentNullException("sourceText");
      
      FilePath = filePath;
      SourceText = sourceText;
      Revision = revision;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, [NotNull] out string sourceText, out long revision)
    {
      filePath = FilePath;
      sourceText = SourceText;
      revision = Revision;
    }
    //statics
    
    public static CtxReadDelegate<MixinExpressionRequest> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var sourceText = reader.ReadString();
      var revision = reader.ReadLong();
      var _result = new MixinExpressionRequest(filePath, sourceText, revision);
      return _result;
    };
    
    public static CtxWriteDelegate<MixinExpressionRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.SourceText);
      writer.Write(value.Revision);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinExpressionRequest) obj);
    }
    public bool Equals(MixinExpressionRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && SourceText == other.SourceText && Revision == other.Revision;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + SourceText.GetHashCode();
        hash = hash * 31 + Revision.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinExpressionRequest (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("sourceText = "); SourceText.PrintEx(printer); printer.Println();
        printer.Print("revision = "); Revision.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:26</p>
  /// </summary>
  public sealed class MixinExpressionResponse : IPrintable, IEquatable<MixinExpressionResponse>
  {
    //fields
    //public fields
    public bool ProjectFileFound {get; private set;}
    public bool CsharpFileFound {get; private set;}
    public int AttributeCount {get; private set;}
    public int MatchedAttributeCount {get; private set;}
    [NotNull] public MixinExpressionRange[] Ranges {get; private set;}
    
    //private fields
    //primary constructor
    public MixinExpressionResponse(
      bool projectFileFound,
      bool csharpFileFound,
      int attributeCount,
      int matchedAttributeCount,
      [NotNull] MixinExpressionRange[] ranges
    )
    {
      if (ranges == null) throw new ArgumentNullException("ranges");
      
      ProjectFileFound = projectFileFound;
      CsharpFileFound = csharpFileFound;
      AttributeCount = attributeCount;
      MatchedAttributeCount = matchedAttributeCount;
      Ranges = ranges;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool projectFileFound, out bool csharpFileFound, out int attributeCount, out int matchedAttributeCount, [NotNull] out MixinExpressionRange[] ranges)
    {
      projectFileFound = ProjectFileFound;
      csharpFileFound = CsharpFileFound;
      attributeCount = AttributeCount;
      matchedAttributeCount = MatchedAttributeCount;
      ranges = Ranges;
    }
    //statics
    
    public static CtxReadDelegate<MixinExpressionResponse> Read = (ctx, reader) => 
    {
      var projectFileFound = reader.ReadBool();
      var csharpFileFound = reader.ReadBool();
      var attributeCount = reader.ReadInt();
      var matchedAttributeCount = reader.ReadInt();
      var ranges = ReadMixinExpressionRangeArray(ctx, reader);
      var _result = new MixinExpressionResponse(projectFileFound, csharpFileFound, attributeCount, matchedAttributeCount, ranges);
      return _result;
    };
    public static CtxReadDelegate<MixinExpressionRange[]> ReadMixinExpressionRangeArray = MixinExpressionRange.Read.Array();
    
    public static CtxWriteDelegate<MixinExpressionResponse> Write = (ctx, writer, value) => 
    {
      writer.Write(value.ProjectFileFound);
      writer.Write(value.CsharpFileFound);
      writer.Write(value.AttributeCount);
      writer.Write(value.MatchedAttributeCount);
      WriteMixinExpressionRangeArray(ctx, writer, value.Ranges);
    };
    public static  CtxWriteDelegate<MixinExpressionRange[]> WriteMixinExpressionRangeArray = MixinExpressionRange.Write.Array();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinExpressionResponse) obj);
    }
    public bool Equals(MixinExpressionResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ProjectFileFound == other.ProjectFileFound && CsharpFileFound == other.CsharpFileFound && AttributeCount == other.AttributeCount && MatchedAttributeCount == other.MatchedAttributeCount && Ranges.SequenceEqual(other.Ranges);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + ProjectFileFound.GetHashCode();
        hash = hash * 31 + CsharpFileFound.GetHashCode();
        hash = hash * 31 + AttributeCount.GetHashCode();
        hash = hash * 31 + MatchedAttributeCount.GetHashCode();
        hash = hash * 31 + Ranges.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinExpressionResponse (");
      using (printer.IndentCookie()) {
        printer.Print("projectFileFound = "); ProjectFileFound.PrintEx(printer); printer.Println();
        printer.Print("csharpFileFound = "); CsharpFileFound.PrintEx(printer); printer.Println();
        printer.Print("attributeCount = "); AttributeCount.PrintEx(printer); printer.Println();
        printer.Print("matchedAttributeCount = "); MatchedAttributeCount.PrintEx(printer); printer.Println();
        printer.Print("ranges = "); Ranges.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
