//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace HelixRider.Protocol
{
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:9</p>
  /// </summary>
  public class HelixExpressionModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<MixinExpressionRequest, MixinExpressionResponse> GetMixinExpressionRanges => _GetMixinExpressionRanges;
    [NotNull] public IViewableProperty<bool> IsHelixEnabled => _IsHelixEnabled;
    
    //private fields
    [NotNull] private readonly RdCall<MixinExpressionRequest, MixinExpressionResponse> _GetMixinExpressionRanges;
    [NotNull] private readonly RdProperty<bool> _IsHelixEnabled;
    
    //primary constructor
    private HelixExpressionModel(
      [NotNull] RdCall<MixinExpressionRequest, MixinExpressionResponse> getMixinExpressionRanges,
      [NotNull] RdProperty<bool> isHelixEnabled
    )
    {
      if (getMixinExpressionRanges == null) throw new ArgumentNullException("getMixinExpressionRanges");
      if (isHelixEnabled == null) throw new ArgumentNullException("isHelixEnabled");
      
      _GetMixinExpressionRanges = getMixinExpressionRanges;
      _IsHelixEnabled = isHelixEnabled;
      _IsHelixEnabled.OptimizeNested = true;
      _GetMixinExpressionRanges.Async = true;
      BindableChildren.Add(new KeyValuePair<string, object>("getMixinExpressionRanges", _GetMixinExpressionRanges));
      BindableChildren.Add(new KeyValuePair<string, object>("isHelixEnabled", _IsHelixEnabled));
    }
    //secondary constructor
    internal HelixExpressionModel (
    ) : this (
      new RdCall<MixinExpressionRequest, MixinExpressionResponse>(MixinExpressionRequest.Read, MixinExpressionRequest.Write, MixinExpressionResponse.Read, MixinExpressionResponse.Write),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => 936167363852658719L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(JetBrains.Rider.Model.IdeRoot), JetBrains.Rider.Model.IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("HelixExpressionModel (");
      using (printer.IndentCookie()) {
        printer.Print("getMixinExpressionRanges = "); _GetMixinExpressionRanges.PrintEx(printer); printer.Println();
        printer.Print("isHelixEnabled = "); _IsHelixEnabled.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionHelixExpressionModelEx
   {
    public static HelixExpressionModel GetHelixExpressionModel(this JetBrains.Rider.Model.Solution solution)
    {
      return solution.GetOrCreateExtension("helixExpressionModel", () => new HelixExpressionModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:15</p>
  /// </summary>
  public sealed class MixinExpressionRange : IPrintable, IEquatable<MixinExpressionRange>
  {
    //fields
    //public fields
    public int StartOffset {get; private set;}
    public int EndOffset {get; private set;}
    
    //private fields
    //primary constructor
    public MixinExpressionRange(
      int startOffset,
      int endOffset
    )
    {
      StartOffset = startOffset;
      EndOffset = endOffset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out int startOffset, out int endOffset)
    {
      startOffset = StartOffset;
      endOffset = EndOffset;
    }
    //statics
    
    public static CtxReadDelegate<MixinExpressionRange> Read = (ctx, reader) => 
    {
      var startOffset = reader.ReadInt();
      var endOffset = reader.ReadInt();
      var _result = new MixinExpressionRange(startOffset, endOffset);
      return _result;
    };
    
    public static CtxWriteDelegate<MixinExpressionRange> Write = (ctx, writer, value) => 
    {
      writer.Write(value.StartOffset);
      writer.Write(value.EndOffset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinExpressionRange) obj);
    }
    public bool Equals(MixinExpressionRange other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return StartOffset == other.StartOffset && EndOffset == other.EndOffset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + StartOffset.GetHashCode();
        hash = hash * 31 + EndOffset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinExpressionRange (");
      using (printer.IndentCookie()) {
        printer.Print("startOffset = "); StartOffset.PrintEx(printer); printer.Println();
        printer.Print("endOffset = "); EndOffset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:20</p>
  /// </summary>
  public sealed class MixinExpressionRequest : IPrintable, IEquatable<MixinExpressionRequest>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    [NotNull] public string SourceText {get; private set;}
    public long Revision {get; private set;}
    
    //private fields
    //primary constructor
    public MixinExpressionRequest(
      [NotNull] string filePath,
      [NotNull] string sourceText,
      long revision
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      if (sourceText == null) throw new ArgumentNullException("sourceText");
      
      FilePath = filePath;
      SourceText = sourceText;
      Revision = revision;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, [NotNull] out string sourceText, out long revision)
    {
      filePath = FilePath;
      sourceText = SourceText;
      revision = Revision;
    }
    //statics
    
    public static CtxReadDelegate<MixinExpressionRequest> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var sourceText = reader.ReadString();
      var revision = reader.ReadLong();
      var _result = new MixinExpressionRequest(filePath, sourceText, revision);
      return _result;
    };
    
    public static CtxWriteDelegate<MixinExpressionRequest> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.SourceText);
      writer.Write(value.Revision);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinExpressionRequest) obj);
    }
    public bool Equals(MixinExpressionRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && SourceText == other.SourceText && Revision == other.Revision;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + SourceText.GetHashCode();
        hash = hash * 31 + Revision.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinExpressionRequest (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("sourceText = "); SourceText.PrintEx(printer); printer.Println();
        printer.Print("revision = "); Revision.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: HelixExpressionModel.kt:26</p>
  /// </summary>
  public sealed class MixinExpressionResponse : IPrintable, IEquatable<MixinExpressionResponse>
  {
    //fields
    //public fields
    public bool ProjectFileFound {get; private set;}
    public bool CsharpFileFound {get; private set;}
    public int AttributeCount {get; private set;}
    public int MatchedAttributeCount {get; private set;}
    [NotNull] public MixinExpressionRange[] Ranges {get; private set;}
    
    //private fields
    //primary constructor
    public MixinExpressionResponse(
      bool projectFileFound,
      bool csharpFileFound,
      int attributeCount,
      int matchedAttributeCount,
      [NotNull] MixinExpressionRange[] ranges
    )
    {
      if (ranges == null) throw new ArgumentNullException("ranges");
      
      ProjectFileFound = projectFileFound;
      CsharpFileFound = csharpFileFound;
      AttributeCount = attributeCount;
      MatchedAttributeCount = matchedAttributeCount;
      Ranges = ranges;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool projectFileFound, out bool csharpFileFound, out int attributeCount, out int matchedAttributeCount, [NotNull] out MixinExpressionRange[] ranges)
    {
      projectFileFound = ProjectFileFound;
      csharpFileFound = CsharpFileFound;
      attributeCount = AttributeCount;
      matchedAttributeCount = MatchedAttributeCount;
      ranges = Ranges;
    }
    //statics
    
    public static CtxReadDelegate<MixinExpressionResponse> Read = (ctx, reader) => 
    {
      var projectFileFound = reader.ReadBool();
      var csharpFileFound = reader.ReadBool();
      var attributeCount = reader.ReadInt();
      var matchedAttributeCount = reader.ReadInt();
      var ranges = ReadMixinExpressionRangeArray(ctx, reader);
      var _result = new MixinExpressionResponse(projectFileFound, csharpFileFound, attributeCount, matchedAttributeCount, ranges);
      return _result;
    };
    public static CtxReadDelegate<MixinExpressionRange[]> ReadMixinExpressionRangeArray = MixinExpressionRange.Read.Array();
    
    public static CtxWriteDelegate<MixinExpressionResponse> Write = (ctx, writer, value) => 
    {
      writer.Write(value.ProjectFileFound);
      writer.Write(value.CsharpFileFound);
      writer.Write(value.AttributeCount);
      writer.Write(value.MatchedAttributeCount);
      WriteMixinExpressionRangeArray(ctx, writer, value.Ranges);
    };
    public static  CtxWriteDelegate<MixinExpressionRange[]> WriteMixinExpressionRangeArray = MixinExpressionRange.Write.Array();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((MixinExpressionResponse) obj);
    }
    public bool Equals(MixinExpressionResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ProjectFileFound == other.ProjectFileFound && CsharpFileFound == other.CsharpFileFound && AttributeCount == other.AttributeCount && MatchedAttributeCount == other.MatchedAttributeCount && Ranges.SequenceEqual(other.Ranges);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + ProjectFileFound.GetHashCode();
        hash = hash * 31 + CsharpFileFound.GetHashCode();
        hash = hash * 31 + AttributeCount.GetHashCode();
        hash = hash * 31 + MatchedAttributeCount.GetHashCode();
        hash = hash * 31 + Ranges.ContentHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("MixinExpressionResponse (");
      using (printer.IndentCookie()) {
        printer.Print("projectFileFound = "); ProjectFileFound.PrintEx(printer); printer.Println();
        printer.Print("csharpFileFound = "); CsharpFileFound.PrintEx(printer); printer.Println();
        printer.Print("attributeCount = "); AttributeCount.PrintEx(printer); printer.Println();
        printer.Print("matchedAttributeCount = "); MatchedAttributeCount.PrintEx(printer); printer.Println();
        printer.Print("ranges = "); Ranges.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
