using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HELIX.SourceGen {
  [Generator(LanguageNames.CSharp)]
  public sealed class BoundaryVisualElementGenerator : IIncrementalGenerator {
    private const string UxmlElementAttributeMetadataName = "UnityEngine.UIElements.UxmlElementAttribute";
    private const string BoundaryVisualElementTypeName = "HELIX.Compose.BoundaryVisualElement";
    private const string CompositionTypeName = "HELIX.Compose.Composition";
    private const string CompositionIdTypeName = "HELIX.Compose.CompositionId";
    private const string LocalIdTypeName = "HELIX.Compose.LocalId";

    public void Initialize(IncrementalGeneratorInitializationContext context) {
      var elements = context.SyntaxProvider.ForAttributeWithMetadataName(
        UxmlElementAttributeMetadataName,
        predicate: static (node, _) => node is ClassDeclarationSyntax,
        transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol
      );

      context.RegisterSourceOutput(elements, static (spc, element) => Generate(spc, element));
    }

    private static void Generate(SourceProductionContext spc, INamedTypeSymbol element) {
      if (!InheritsFromBoundaryVisualElement(element)) return;

      var containing = BuildContainingTypeWrapper(element, out var hintName);
      var body = $@"
    private static readonly global::{CompositionIdTypeName} _compositionId = new() {{
      composition = global::{CompositionIdTypeName}.GetCompositionId(),
      type = global::{CompositionIdTypeName}.GetTypeId(),
      local = global::{LocalIdTypeName}.Initial
    }};

    public override void PerformCompose(ref global::{CompositionTypeName} cx) {{
      cx.AUTHORING.SetId(_compositionId);
      Compose(ref cx);
    }}
";

      spc.AddSource(hintName, containing.Header + body + containing.Footer);
    }

    private static bool InheritsFromBoundaryVisualElement(INamedTypeSymbol type) {
      for (var baseType = type.BaseType; baseType is not null; baseType = baseType.BaseType) {
        if (baseType.ToDisplayString() == BoundaryVisualElementTypeName) return true;
      }

      return false;
    }

    private static (string Header, string Footer) BuildContainingTypeWrapper(
      INamedTypeSymbol type,
      out string hintName
    ) {
      var chain = new List<INamedTypeSymbol>();
      for (var current = type; current is not null; current = current.ContainingType) {
        chain.Add(current);
      }
      chain.Reverse();

      var ns = type.ContainingNamespace is { IsGlobalNamespace: false } n
        ? n.ToDisplayString()
        : null;
      var header = "// <auto-generated/>\n";
      var footer = "";
      var depth = 0;

      if (ns is not null) {
        header += "namespace " + ns + " {\n";
        depth = 1;
      }

      foreach (var current in chain) {
        header += new string(' ', depth * 2) + "partial " + KeywordFor(current) + " " +
                  current.Name + TypeParametersFor(current) + " {\n";
        depth++;
      }

      for (var i = depth - 1; i >= 0; i--) {
        footer += new string(' ', i * 2) + "}\n";
      }

      var hintBase = (ns ?? "global") + "." +
                     string.Join(".", chain.Select(current => current.MetadataName)) +
                     ".boundary-visual-element";
      hintName = Sanitize(hintBase) + ".g.cs";
      return (header, footer);
    }

    private static string KeywordFor(INamedTypeSymbol type) => type.IsRecord ? "record" : "class";

    private static string TypeParametersFor(INamedTypeSymbol type) => type.TypeParameters.Length == 0
      ? ""
      : "<" + string.Join(", ", type.TypeParameters.Select(parameter => parameter.Name)) + ">";

    private static string Sanitize(string value) {
      var characters = value.ToCharArray();
      for (var i = 0; i < characters.Length; i++) {
        if (!char.IsLetterOrDigit(characters[i])) characters[i] = '_';
      }
      return new string(characters);
    }
  }
}
