using System;
using System.Collections.Generic;
using System.Text;

namespace Mixins.Roslyn;

/// <summary>Builds consistently indented C# source with disposable delimiter scopes.</summary>
internal sealed class SharpStringBuilder {
  private readonly StringBuilder _builder = new();
  private readonly string _indentText;
  private bool _atLineStart = true;

  internal SharpStringBuilder(string indentText = "  ") {
    _indentText = indentText ?? throw new ArgumentNullException(nameof(indentText));
  }

  internal int IndentLevel { get; private set; }

  internal SharpStringBuilder Append(string value) {
    if (string.IsNullOrEmpty(value)) return this;
    var normalized = value.Replace("\r\n", "\n").Replace('\r', '\n');
    foreach (var character in normalized) {
      if (_atLineStart && character != '\n') {
        for (var level = 0; level < IndentLevel; level++) _builder.Append(_indentText);
        _atLineStart = false;
      }
      _builder.Append(character);
      if (character == '\n') _atLineStart = true;
    }
    return this;
  }

  internal SharpStringBuilder AppendLine(string value = null) {
    Append(value);
    _builder.Append('\n');
    _atLineStart = true;
    return this;
  }

  internal SharpStringBuilder AppendCode(string code) {
    if (string.IsNullOrEmpty(code)) return this;
    var normalized = code.Replace("\r\n", "\n").Replace('\r', '\n').TrimEnd('\n');
    foreach (var line in normalized.Split(['\n'], StringSplitOptions.None)) AppendLine(line);
    return this;
  }

  internal SharpStringBuilder BlankLine() {
    return AppendLine();
  }

  internal SharpStringBuilder GeneratedFile() {
    return AppendLine("// <auto-generated/>");
  }

  internal SharpStringBuilder Using(string directive) {
    return AppendLine("using " + directive.Trim() + ";");
  }

  internal SharpStringBuilder Attribute(string attribute) {
    return AppendLine("[" + attribute + "]");
  }

  internal SharpStringBuilder Statement(string statement) {
    return AppendLine(statement.EndsWith(";", StringComparison.Ordinal) ? statement : statement + ";");
  }

  internal SharpStringBuilder Assignment(string target, string value) {
    return Statement(target + " = " + value);
  }

  internal SharpStringBuilder Return(string expression, bool byRef = false) {
    return Statement("return " + (byRef ? "ref " : "") + expression);
  }

  internal SharpStringBuilder Field(string modifiers, string type, string name, string value = null) {
    Append(modifiers).Append(" ").Append(type).Append(" ").Append(name);
    if (value is not null) Append(" = ").Append(value);
    return AppendLine(";");
  }

  internal SharpStringBuilder AppendList<T>(
    IEnumerable<T> values,
    Action<SharpStringBuilder, T> append,
    string separator = ", "
  ) {
    var first = true;
    foreach (var value in values) {
      if (!first) Append(separator);
      append(this, value);
      first = false;
    }
    return this;
  }

  internal SharpStringBuilder AppendList(IEnumerable<string> values, string separator = ", ") {
    return AppendList(values, static (builder, value) => builder.Append(value), separator);
  }

  internal SharpStringBuilder AppendDelimitedList(
    IEnumerable<string> values,
    string opening = "(",
    string closing = ")",
    bool multiline = false
  ) {
    var items = values as IReadOnlyList<string> ?? [.. values];
    if (!multiline || items.Count == 0) {
      Append(opening).AppendList(items).Append(closing);
      return this;
    }

    using (Delimited(opening, closing, closeLine: false)) {
      for (var index = 0; index < items.Count; index++) {
        Append(items[index]);
        AppendLine(index == items.Count - 1 ? null : ",");
      }
    }
    return this;
  }

  internal SharpStringBuilder Parameters(IEnumerable<string> parameters, bool multiline = true) {
    return AppendDelimitedList(parameters, multiline: multiline);
  }

  internal SharpStringBuilder Arguments(IEnumerable<string> arguments) {
    return AppendDelimitedList(arguments, multiline: false);
  }

  internal IDisposable Namespace(string name) {
    return string.IsNullOrEmpty(name) ? EmptyScope.Instance : Block("namespace " + name);
  }

  internal IDisposable Type(string declaration) {
    return Block(declaration);
  }

  internal IDisposable Method(
    string declaration,
    IEnumerable<string> parameters,
    bool multiline = true
  ) {
    Append(declaration).Parameters(parameters, multiline);
    return Block();
  }

  internal IDisposable If(string condition) {
    return Block("if (" + condition + ")");
  }

  internal IDisposable Try() {
    return Block("try");
  }

  internal IDisposable Finally() {
    return Block("finally");
  }

  internal IDisposable Block(string header = null, string suffix = null) {
    if (!string.IsNullOrEmpty(header)) Append(header);
    Append(_atLineStart ? "{" : " {");
    return OpenScope("}", suffix, true);
  }

  internal IDisposable Delimited(
    string opening,
    string closing,
    string suffix = null,
    bool closeLine = true
  ) {
    Append(opening);
    return OpenScope(closing, suffix, closeLine);
  }

  public override string ToString() {
    return _builder.ToString();
  }

  private IDisposable OpenScope(string closing, string suffix, bool closeLine) {
    AppendLine();
    IndentLevel++;
    return new Scope(this, IndentLevel, closing, suffix, closeLine);
  }

  private void CloseScope(int depth, string closing, string suffix, bool closeLine) {
    if (IndentLevel != depth)
      throw new InvalidOperationException("SharpStringBuilder scopes must be disposed in reverse order.");
    IndentLevel--;
    Append(closing).Append(suffix);
    if (closeLine) AppendLine();
  }

  private sealed class Scope : IDisposable {
    private readonly bool _closeLine;
    private readonly string _closing;
    private readonly int _depth;
    private readonly string _suffix;
    private SharpStringBuilder _owner;

    internal Scope(SharpStringBuilder owner, int depth, string closing, string suffix, bool closeLine) {
      _owner = owner;
      _depth = depth;
      _closing = closing;
      _suffix = suffix;
      _closeLine = closeLine;
    }

    public void Dispose() {
      var owner = _owner;
      if (owner is null) return;
      _owner = null;
      owner.CloseScope(_depth, _closing, _suffix, _closeLine);
    }
  }

  private sealed class EmptyScope : IDisposable {
    internal static EmptyScope Instance { get; } = new();

    public void Dispose() { }
  }
}